# Generated by Django 4.2.1 on 2023-08-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_field',
        ),
    ]
