# Generated by Django 4.2.3 on 2023-08-04 00:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_image_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='xc', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[500, 500], upload_to='post_images/'),
        ),
    ]
